package exam.entities;

import java.time.LocalDate;

public class Person {

    private String cccd;

    private String hoTen;

    private String ngaySinh;

    private String gioiTinh;

    private String soDienThoai;

    private String email;

    private String soTheBhyt;

    private String ngheNghiep;

    private String diaChi;

    private String ngayDangKy = LocalDate.now().toString();

    private Integer trangThaiTiem = 1;


    public String getCccd() {
        return cccd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.CCCD
     *
     * @param cccd the value for Person.CCCD
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public void setCccd(String cccd) {
        this.cccd = cccd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.ho_ten
     *
     * @return the value of Person.ho_ten
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public String getHoTen() {
        return hoTen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.ho_ten
     *
     * @param hoTen the value for Person.ho_ten
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.ngay_sinh
     *
     * @return the value of Person.ngay_sinh
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public String getNgaySinh() {
        return ngaySinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.ngay_sinh
     *
     * @param ngaySinh the value for Person.ngay_sinh
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public void setNgaySinh(String ngaySinh) {
        this.ngaySinh = ngaySinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.gioi_tinh
     *
     * @return the value of Person.gioi_tinh
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public String getGioiTinh() {
        return gioiTinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.gioi_tinh
     *
     * @param gioiTinh the value for Person.gioi_tinh
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public void setGioiTinh(String gioiTinh) {
        this.gioiTinh = gioiTinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.so_dien_thoai
     *
     * @return the value of Person.so_dien_thoai
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public String getSoDienThoai() {
        return soDienThoai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.so_dien_thoai
     *
     * @param soDienThoai the value for Person.so_dien_thoai
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public void setSoDienThoai(String soDienThoai) {
        this.soDienThoai = soDienThoai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.email
     *
     * @return the value of Person.email
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.email
     *
     * @param email the value for Person.email
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.so_the_BHYT
     *
     * @return the value of Person.so_the_BHYT
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public String getSoTheBhyt() {
        return soTheBhyt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.so_the_BHYT
     *
     * @param soTheBhyt the value for Person.so_the_BHYT
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public void setSoTheBhyt(String soTheBhyt) {
        this.soTheBhyt = soTheBhyt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.nghe_nghiep
     *
     * @return the value of Person.nghe_nghiep
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public String getNgheNghiep() {
        return ngheNghiep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.nghe_nghiep
     *
     * @param ngheNghiep the value for Person.nghe_nghiep
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public void setNgheNghiep(String ngheNghiep) {
        this.ngheNghiep = ngheNghiep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.dia_chi
     *
     * @return the value of Person.dia_chi
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public String getDiaChi() {
        return diaChi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.dia_chi
     *
     * @param diaChi the value for Person.dia_chi
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.ngay_dang_ky
     *
     * @return the value of Person.ngay_dang_ky
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public String getNgayDangKy() {
        return ngayDangKy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.ngay_dang_ky
     *
     * @param ngayDangKy the value for Person.ngay_dang_ky
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public void setNgayDangKy(String ngayDangKy) {
        this.ngayDangKy = ngayDangKy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.trang_thai_tiem
     *
     * @return the value of Person.trang_thai_tiem
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public Integer getTrangThaiTiem() {
        return trangThaiTiem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.trang_thai_tiem
     *
     * @param trangThaiTiem the value for Person.trang_thai_tiem
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public void setTrangThaiTiem(Integer trangThaiTiem) {
        this.trangThaiTiem = trangThaiTiem;
    }


    @Override
    public String toString() {
        return "Person{" +
                "cccd='" + cccd + '\'' +
                ", hoTen='" + hoTen + '\'' +
                ", ngaySinh='" + ngaySinh + '\'' +
                ", gioiTinh='" + gioiTinh + '\'' +
                ", soDienThoai='" + soDienThoai + '\'' +
                ", email='" + email + '\'' +
                ", soTheBhyt='" + soTheBhyt + '\'' +
                ", ngheNghiep='" + ngheNghiep + '\'' +
                ", diaChi='" + diaChi + '\'' +
                ", ngayDangKy='" + ngayDangKy + '\'' +
                ", trangThaiTiem=" + trangThaiTiem +
                '}';
    }
}