package exam.entities;

import java.util.ArrayList;
import java.util.List;

public class PersonExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Person
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Person
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Person
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Person
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public PersonExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Person
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Person
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Person
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Person
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Person
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Person
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Person
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Person
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Person
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Person
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Person
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCccdIsNull() {
            addCriterion("CCCD is null");
            return (Criteria) this;
        }

        public Criteria andCccdIsNotNull() {
            addCriterion("CCCD is not null");
            return (Criteria) this;
        }

        public Criteria andCccdEqualTo(String value) {
            addCriterion("CCCD =", value, "cccd");
            return (Criteria) this;
        }

        public Criteria andCccdNotEqualTo(String value) {
            addCriterion("CCCD <>", value, "cccd");
            return (Criteria) this;
        }

        public Criteria andCccdGreaterThan(String value) {
            addCriterion("CCCD >", value, "cccd");
            return (Criteria) this;
        }

        public Criteria andCccdGreaterThanOrEqualTo(String value) {
            addCriterion("CCCD >=", value, "cccd");
            return (Criteria) this;
        }

        public Criteria andCccdLessThan(String value) {
            addCriterion("CCCD <", value, "cccd");
            return (Criteria) this;
        }

        public Criteria andCccdLessThanOrEqualTo(String value) {
            addCriterion("CCCD <=", value, "cccd");
            return (Criteria) this;
        }

        public Criteria andCccdLike(String value) {
            addCriterion("CCCD like", value, "cccd");
            return (Criteria) this;
        }

        public Criteria andCccdNotLike(String value) {
            addCriterion("CCCD not like", value, "cccd");
            return (Criteria) this;
        }

        public Criteria andCccdIn(List<String> values) {
            addCriterion("CCCD in", values, "cccd");
            return (Criteria) this;
        }

        public Criteria andCccdNotIn(List<String> values) {
            addCriterion("CCCD not in", values, "cccd");
            return (Criteria) this;
        }

        public Criteria andCccdBetween(String value1, String value2) {
            addCriterion("CCCD between", value1, value2, "cccd");
            return (Criteria) this;
        }

        public Criteria andCccdNotBetween(String value1, String value2) {
            addCriterion("CCCD not between", value1, value2, "cccd");
            return (Criteria) this;
        }

        public Criteria andHoTenIsNull() {
            addCriterion("ho_ten is null");
            return (Criteria) this;
        }

        public Criteria andHoTenIsNotNull() {
            addCriterion("ho_ten is not null");
            return (Criteria) this;
        }

        public Criteria andHoTenEqualTo(String value) {
            addCriterion("ho_ten =", value, "hoTen");
            return (Criteria) this;
        }

        public Criteria andHoTenNotEqualTo(String value) {
            addCriterion("ho_ten <>", value, "hoTen");
            return (Criteria) this;
        }

        public Criteria andHoTenGreaterThan(String value) {
            addCriterion("ho_ten >", value, "hoTen");
            return (Criteria) this;
        }

        public Criteria andHoTenGreaterThanOrEqualTo(String value) {
            addCriterion("ho_ten >=", value, "hoTen");
            return (Criteria) this;
        }

        public Criteria andHoTenLessThan(String value) {
            addCriterion("ho_ten <", value, "hoTen");
            return (Criteria) this;
        }

        public Criteria andHoTenLessThanOrEqualTo(String value) {
            addCriterion("ho_ten <=", value, "hoTen");
            return (Criteria) this;
        }

        public Criteria andHoTenLike(String value) {
            addCriterion("ho_ten like", value, "hoTen");
            return (Criteria) this;
        }

        public Criteria andHoTenNotLike(String value) {
            addCriterion("ho_ten not like", value, "hoTen");
            return (Criteria) this;
        }

        public Criteria andHoTenIn(List<String> values) {
            addCriterion("ho_ten in", values, "hoTen");
            return (Criteria) this;
        }

        public Criteria andHoTenNotIn(List<String> values) {
            addCriterion("ho_ten not in", values, "hoTen");
            return (Criteria) this;
        }

        public Criteria andHoTenBetween(String value1, String value2) {
            addCriterion("ho_ten between", value1, value2, "hoTen");
            return (Criteria) this;
        }

        public Criteria andHoTenNotBetween(String value1, String value2) {
            addCriterion("ho_ten not between", value1, value2, "hoTen");
            return (Criteria) this;
        }

        public Criteria andNgaySinhIsNull() {
            addCriterion("ngay_sinh is null");
            return (Criteria) this;
        }

        public Criteria andNgaySinhIsNotNull() {
            addCriterion("ngay_sinh is not null");
            return (Criteria) this;
        }

        public Criteria andNgaySinhEqualTo(String value) {
            addCriterion("ngay_sinh =", value, "ngaySinh");
            return (Criteria) this;
        }

        public Criteria andNgaySinhNotEqualTo(String value) {
            addCriterion("ngay_sinh <>", value, "ngaySinh");
            return (Criteria) this;
        }

        public Criteria andNgaySinhGreaterThan(String value) {
            addCriterion("ngay_sinh >", value, "ngaySinh");
            return (Criteria) this;
        }

        public Criteria andNgaySinhGreaterThanOrEqualTo(String value) {
            addCriterion("ngay_sinh >=", value, "ngaySinh");
            return (Criteria) this;
        }

        public Criteria andNgaySinhLessThan(String value) {
            addCriterion("ngay_sinh <", value, "ngaySinh");
            return (Criteria) this;
        }

        public Criteria andNgaySinhLessThanOrEqualTo(String value) {
            addCriterion("ngay_sinh <=", value, "ngaySinh");
            return (Criteria) this;
        }

        public Criteria andNgaySinhLike(String value) {
            addCriterion("ngay_sinh like", value, "ngaySinh");
            return (Criteria) this;
        }

        public Criteria andNgaySinhNotLike(String value) {
            addCriterion("ngay_sinh not like", value, "ngaySinh");
            return (Criteria) this;
        }

        public Criteria andNgaySinhIn(List<String> values) {
            addCriterion("ngay_sinh in", values, "ngaySinh");
            return (Criteria) this;
        }

        public Criteria andNgaySinhNotIn(List<String> values) {
            addCriterion("ngay_sinh not in", values, "ngaySinh");
            return (Criteria) this;
        }

        public Criteria andNgaySinhBetween(String value1, String value2) {
            addCriterion("ngay_sinh between", value1, value2, "ngaySinh");
            return (Criteria) this;
        }

        public Criteria andNgaySinhNotBetween(String value1, String value2) {
            addCriterion("ngay_sinh not between", value1, value2, "ngaySinh");
            return (Criteria) this;
        }

        public Criteria andGioiTinhIsNull() {
            addCriterion("gioi_tinh is null");
            return (Criteria) this;
        }

        public Criteria andGioiTinhIsNotNull() {
            addCriterion("gioi_tinh is not null");
            return (Criteria) this;
        }

        public Criteria andGioiTinhEqualTo(String value) {
            addCriterion("gioi_tinh =", value, "gioiTinh");
            return (Criteria) this;
        }

        public Criteria andGioiTinhNotEqualTo(String value) {
            addCriterion("gioi_tinh <>", value, "gioiTinh");
            return (Criteria) this;
        }

        public Criteria andGioiTinhGreaterThan(String value) {
            addCriterion("gioi_tinh >", value, "gioiTinh");
            return (Criteria) this;
        }

        public Criteria andGioiTinhGreaterThanOrEqualTo(String value) {
            addCriterion("gioi_tinh >=", value, "gioiTinh");
            return (Criteria) this;
        }

        public Criteria andGioiTinhLessThan(String value) {
            addCriterion("gioi_tinh <", value, "gioiTinh");
            return (Criteria) this;
        }

        public Criteria andGioiTinhLessThanOrEqualTo(String value) {
            addCriterion("gioi_tinh <=", value, "gioiTinh");
            return (Criteria) this;
        }

        public Criteria andGioiTinhLike(String value) {
            addCriterion("gioi_tinh like", value, "gioiTinh");
            return (Criteria) this;
        }

        public Criteria andGioiTinhNotLike(String value) {
            addCriterion("gioi_tinh not like", value, "gioiTinh");
            return (Criteria) this;
        }

        public Criteria andGioiTinhIn(List<String> values) {
            addCriterion("gioi_tinh in", values, "gioiTinh");
            return (Criteria) this;
        }

        public Criteria andGioiTinhNotIn(List<String> values) {
            addCriterion("gioi_tinh not in", values, "gioiTinh");
            return (Criteria) this;
        }

        public Criteria andGioiTinhBetween(String value1, String value2) {
            addCriterion("gioi_tinh between", value1, value2, "gioiTinh");
            return (Criteria) this;
        }

        public Criteria andGioiTinhNotBetween(String value1, String value2) {
            addCriterion("gioi_tinh not between", value1, value2, "gioiTinh");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiIsNull() {
            addCriterion("so_dien_thoai is null");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiIsNotNull() {
            addCriterion("so_dien_thoai is not null");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiEqualTo(String value) {
            addCriterion("so_dien_thoai =", value, "soDienThoai");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiNotEqualTo(String value) {
            addCriterion("so_dien_thoai <>", value, "soDienThoai");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiGreaterThan(String value) {
            addCriterion("so_dien_thoai >", value, "soDienThoai");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiGreaterThanOrEqualTo(String value) {
            addCriterion("so_dien_thoai >=", value, "soDienThoai");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiLessThan(String value) {
            addCriterion("so_dien_thoai <", value, "soDienThoai");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiLessThanOrEqualTo(String value) {
            addCriterion("so_dien_thoai <=", value, "soDienThoai");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiLike(String value) {
            addCriterion("so_dien_thoai like", value, "soDienThoai");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiNotLike(String value) {
            addCriterion("so_dien_thoai not like", value, "soDienThoai");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiIn(List<String> values) {
            addCriterion("so_dien_thoai in", values, "soDienThoai");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiNotIn(List<String> values) {
            addCriterion("so_dien_thoai not in", values, "soDienThoai");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiBetween(String value1, String value2) {
            addCriterion("so_dien_thoai between", value1, value2, "soDienThoai");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiNotBetween(String value1, String value2) {
            addCriterion("so_dien_thoai not between", value1, value2, "soDienThoai");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andSoTheBhytIsNull() {
            addCriterion("so_the_BHYT is null");
            return (Criteria) this;
        }

        public Criteria andSoTheBhytIsNotNull() {
            addCriterion("so_the_BHYT is not null");
            return (Criteria) this;
        }

        public Criteria andSoTheBhytEqualTo(String value) {
            addCriterion("so_the_BHYT =", value, "soTheBhyt");
            return (Criteria) this;
        }

        public Criteria andSoTheBhytNotEqualTo(String value) {
            addCriterion("so_the_BHYT <>", value, "soTheBhyt");
            return (Criteria) this;
        }

        public Criteria andSoTheBhytGreaterThan(String value) {
            addCriterion("so_the_BHYT >", value, "soTheBhyt");
            return (Criteria) this;
        }

        public Criteria andSoTheBhytGreaterThanOrEqualTo(String value) {
            addCriterion("so_the_BHYT >=", value, "soTheBhyt");
            return (Criteria) this;
        }

        public Criteria andSoTheBhytLessThan(String value) {
            addCriterion("so_the_BHYT <", value, "soTheBhyt");
            return (Criteria) this;
        }

        public Criteria andSoTheBhytLessThanOrEqualTo(String value) {
            addCriterion("so_the_BHYT <=", value, "soTheBhyt");
            return (Criteria) this;
        }

        public Criteria andSoTheBhytLike(String value) {
            addCriterion("so_the_BHYT like", value, "soTheBhyt");
            return (Criteria) this;
        }

        public Criteria andSoTheBhytNotLike(String value) {
            addCriterion("so_the_BHYT not like", value, "soTheBhyt");
            return (Criteria) this;
        }

        public Criteria andSoTheBhytIn(List<String> values) {
            addCriterion("so_the_BHYT in", values, "soTheBhyt");
            return (Criteria) this;
        }

        public Criteria andSoTheBhytNotIn(List<String> values) {
            addCriterion("so_the_BHYT not in", values, "soTheBhyt");
            return (Criteria) this;
        }

        public Criteria andSoTheBhytBetween(String value1, String value2) {
            addCriterion("so_the_BHYT between", value1, value2, "soTheBhyt");
            return (Criteria) this;
        }

        public Criteria andSoTheBhytNotBetween(String value1, String value2) {
            addCriterion("so_the_BHYT not between", value1, value2, "soTheBhyt");
            return (Criteria) this;
        }

        public Criteria andNgheNghiepIsNull() {
            addCriterion("nghe_nghiep is null");
            return (Criteria) this;
        }

        public Criteria andNgheNghiepIsNotNull() {
            addCriterion("nghe_nghiep is not null");
            return (Criteria) this;
        }

        public Criteria andNgheNghiepEqualTo(String value) {
            addCriterion("nghe_nghiep =", value, "ngheNghiep");
            return (Criteria) this;
        }

        public Criteria andNgheNghiepNotEqualTo(String value) {
            addCriterion("nghe_nghiep <>", value, "ngheNghiep");
            return (Criteria) this;
        }

        public Criteria andNgheNghiepGreaterThan(String value) {
            addCriterion("nghe_nghiep >", value, "ngheNghiep");
            return (Criteria) this;
        }

        public Criteria andNgheNghiepGreaterThanOrEqualTo(String value) {
            addCriterion("nghe_nghiep >=", value, "ngheNghiep");
            return (Criteria) this;
        }

        public Criteria andNgheNghiepLessThan(String value) {
            addCriterion("nghe_nghiep <", value, "ngheNghiep");
            return (Criteria) this;
        }

        public Criteria andNgheNghiepLessThanOrEqualTo(String value) {
            addCriterion("nghe_nghiep <=", value, "ngheNghiep");
            return (Criteria) this;
        }

        public Criteria andNgheNghiepLike(String value) {
            addCriterion("nghe_nghiep like", value, "ngheNghiep");
            return (Criteria) this;
        }

        public Criteria andNgheNghiepNotLike(String value) {
            addCriterion("nghe_nghiep not like", value, "ngheNghiep");
            return (Criteria) this;
        }

        public Criteria andNgheNghiepIn(List<String> values) {
            addCriterion("nghe_nghiep in", values, "ngheNghiep");
            return (Criteria) this;
        }

        public Criteria andNgheNghiepNotIn(List<String> values) {
            addCriterion("nghe_nghiep not in", values, "ngheNghiep");
            return (Criteria) this;
        }

        public Criteria andNgheNghiepBetween(String value1, String value2) {
            addCriterion("nghe_nghiep between", value1, value2, "ngheNghiep");
            return (Criteria) this;
        }

        public Criteria andNgheNghiepNotBetween(String value1, String value2) {
            addCriterion("nghe_nghiep not between", value1, value2, "ngheNghiep");
            return (Criteria) this;
        }

        public Criteria andDiaChiIsNull() {
            addCriterion("dia_chi is null");
            return (Criteria) this;
        }

        public Criteria andDiaChiIsNotNull() {
            addCriterion("dia_chi is not null");
            return (Criteria) this;
        }

        public Criteria andDiaChiEqualTo(String value) {
            addCriterion("dia_chi =", value, "diaChi");
            return (Criteria) this;
        }

        public Criteria andDiaChiNotEqualTo(String value) {
            addCriterion("dia_chi <>", value, "diaChi");
            return (Criteria) this;
        }

        public Criteria andDiaChiGreaterThan(String value) {
            addCriterion("dia_chi >", value, "diaChi");
            return (Criteria) this;
        }

        public Criteria andDiaChiGreaterThanOrEqualTo(String value) {
            addCriterion("dia_chi >=", value, "diaChi");
            return (Criteria) this;
        }

        public Criteria andDiaChiLessThan(String value) {
            addCriterion("dia_chi <", value, "diaChi");
            return (Criteria) this;
        }

        public Criteria andDiaChiLessThanOrEqualTo(String value) {
            addCriterion("dia_chi <=", value, "diaChi");
            return (Criteria) this;
        }

        public Criteria andDiaChiLike(String value) {
            addCriterion("dia_chi like", value, "diaChi");
            return (Criteria) this;
        }

        public Criteria andDiaChiNotLike(String value) {
            addCriterion("dia_chi not like", value, "diaChi");
            return (Criteria) this;
        }

        public Criteria andDiaChiIn(List<String> values) {
            addCriterion("dia_chi in", values, "diaChi");
            return (Criteria) this;
        }

        public Criteria andDiaChiNotIn(List<String> values) {
            addCriterion("dia_chi not in", values, "diaChi");
            return (Criteria) this;
        }

        public Criteria andDiaChiBetween(String value1, String value2) {
            addCriterion("dia_chi between", value1, value2, "diaChi");
            return (Criteria) this;
        }

        public Criteria andDiaChiNotBetween(String value1, String value2) {
            addCriterion("dia_chi not between", value1, value2, "diaChi");
            return (Criteria) this;
        }

        public Criteria andNgayDangKyIsNull() {
            addCriterion("ngay_dang_ky is null");
            return (Criteria) this;
        }

        public Criteria andNgayDangKyIsNotNull() {
            addCriterion("ngay_dang_ky is not null");
            return (Criteria) this;
        }

        public Criteria andNgayDangKyEqualTo(String value) {
            addCriterion("ngay_dang_ky =", value, "ngayDangKy");
            return (Criteria) this;
        }

        public Criteria andNgayDangKyNotEqualTo(String value) {
            addCriterion("ngay_dang_ky <>", value, "ngayDangKy");
            return (Criteria) this;
        }

        public Criteria andNgayDangKyGreaterThan(String value) {
            addCriterion("ngay_dang_ky >", value, "ngayDangKy");
            return (Criteria) this;
        }

        public Criteria andNgayDangKyGreaterThanOrEqualTo(String value) {
            addCriterion("ngay_dang_ky >=", value, "ngayDangKy");
            return (Criteria) this;
        }

        public Criteria andNgayDangKyLessThan(String value) {
            addCriterion("ngay_dang_ky <", value, "ngayDangKy");
            return (Criteria) this;
        }

        public Criteria andNgayDangKyLessThanOrEqualTo(String value) {
            addCriterion("ngay_dang_ky <=", value, "ngayDangKy");
            return (Criteria) this;
        }

        public Criteria andNgayDangKyLike(String value) {
            addCriterion("ngay_dang_ky like", value, "ngayDangKy");
            return (Criteria) this;
        }

        public Criteria andNgayDangKyNotLike(String value) {
            addCriterion("ngay_dang_ky not like", value, "ngayDangKy");
            return (Criteria) this;
        }

        public Criteria andNgayDangKyIn(List<String> values) {
            addCriterion("ngay_dang_ky in", values, "ngayDangKy");
            return (Criteria) this;
        }

        public Criteria andNgayDangKyNotIn(List<String> values) {
            addCriterion("ngay_dang_ky not in", values, "ngayDangKy");
            return (Criteria) this;
        }

        public Criteria andNgayDangKyBetween(String value1, String value2) {
            addCriterion("ngay_dang_ky between", value1, value2, "ngayDangKy");
            return (Criteria) this;
        }

        public Criteria andNgayDangKyNotBetween(String value1, String value2) {
            addCriterion("ngay_dang_ky not between", value1, value2, "ngayDangKy");
            return (Criteria) this;
        }

        public Criteria andTrangThaiTiemIsNull() {
            addCriterion("trang_thai_tiem is null");
            return (Criteria) this;
        }

        public Criteria andTrangThaiTiemIsNotNull() {
            addCriterion("trang_thai_tiem is not null");
            return (Criteria) this;
        }

        public Criteria andTrangThaiTiemEqualTo(Integer value) {
            addCriterion("trang_thai_tiem =", value, "trangThaiTiem");
            return (Criteria) this;
        }

        public Criteria andTrangThaiTiemNotEqualTo(Integer value) {
            addCriterion("trang_thai_tiem <>", value, "trangThaiTiem");
            return (Criteria) this;
        }

        public Criteria andTrangThaiTiemGreaterThan(Integer value) {
            addCriterion("trang_thai_tiem >", value, "trangThaiTiem");
            return (Criteria) this;
        }

        public Criteria andTrangThaiTiemGreaterThanOrEqualTo(Integer value) {
            addCriterion("trang_thai_tiem >=", value, "trangThaiTiem");
            return (Criteria) this;
        }

        public Criteria andTrangThaiTiemLessThan(Integer value) {
            addCriterion("trang_thai_tiem <", value, "trangThaiTiem");
            return (Criteria) this;
        }

        public Criteria andTrangThaiTiemLessThanOrEqualTo(Integer value) {
            addCriterion("trang_thai_tiem <=", value, "trangThaiTiem");
            return (Criteria) this;
        }

        public Criteria andTrangThaiTiemIn(List<Integer> values) {
            addCriterion("trang_thai_tiem in", values, "trangThaiTiem");
            return (Criteria) this;
        }

        public Criteria andTrangThaiTiemNotIn(List<Integer> values) {
            addCriterion("trang_thai_tiem not in", values, "trangThaiTiem");
            return (Criteria) this;
        }

        public Criteria andTrangThaiTiemBetween(Integer value1, Integer value2) {
            addCriterion("trang_thai_tiem between", value1, value2, "trangThaiTiem");
            return (Criteria) this;
        }

        public Criteria andTrangThaiTiemNotBetween(Integer value1, Integer value2) {
            addCriterion("trang_thai_tiem not between", value1, value2, "trangThaiTiem");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Person
     *
     * @mbg.generated do_not_delete_during_merge Tue Mar 12 13:50:13 ICT 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Person
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}