package exam.entities;

public class TiemChung {

    private Integer maTc;

    private String cccd;

    private String ngayTiem;

    private Long lanTiem;

    private String tenVacXin;

	
    public Integer getMaTc() {
        return maTc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TiemChung.ma_tc
     *
     * @param maTc the value for TiemChung.ma_tc
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public void setMaTc(Integer maTc) {
        this.maTc = maTc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TiemChung.CCCD
     *
     * @return the value of TiemChung.CCCD
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public String getCccd() {
        return cccd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TiemChung.CCCD
     *
     * @param cccd the value for TiemChung.CCCD
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public void setCccd(String cccd) {
        this.cccd = cccd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TiemChung.ngay_tiem
     *
     * @return the value of TiemChung.ngay_tiem
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public String getNgayTiem() {
        return ngayTiem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TiemChung.ngay_tiem
     *
     * @param ngayTiem the value for TiemChung.ngay_tiem
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public void setNgayTiem(String ngayTiem) {
        this.ngayTiem = ngayTiem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TiemChung.lan_tiem
     *
     * @return the value of TiemChung.lan_tiem
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public Long getLanTiem() {
        return lanTiem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TiemChung.lan_tiem
     *
     * @param lanTiem the value for TiemChung.lan_tiem
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public void setLanTiem(Long lanTiem) {
        this.lanTiem = lanTiem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TiemChung.ten_vac_xin
     *
     * @return the value of TiemChung.ten_vac_xin
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public String getTenVacXin() {
        return tenVacXin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TiemChung.ten_vac_xin
     *
     * @param tenVacXin the value for TiemChung.ten_vac_xin
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public void setTenVacXin(String tenVacXin) {
        this.tenVacXin = tenVacXin;
    }
}