package exam.entities;

import java.util.ArrayList;
import java.util.List;

public class TiemChungExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TiemChung
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TiemChung
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TiemChung
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TiemChung
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public TiemChungExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TiemChung
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TiemChung
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TiemChung
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TiemChung
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TiemChung
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TiemChung
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TiemChung
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TiemChung
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TiemChung
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TiemChung
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TiemChung
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMaTcIsNull() {
            addCriterion("ma_tc is null");
            return (Criteria) this;
        }

        public Criteria andMaTcIsNotNull() {
            addCriterion("ma_tc is not null");
            return (Criteria) this;
        }

        public Criteria andMaTcEqualTo(Integer value) {
            addCriterion("ma_tc =", value, "maTc");
            return (Criteria) this;
        }

        public Criteria andMaTcNotEqualTo(Integer value) {
            addCriterion("ma_tc <>", value, "maTc");
            return (Criteria) this;
        }

        public Criteria andMaTcGreaterThan(Integer value) {
            addCriterion("ma_tc >", value, "maTc");
            return (Criteria) this;
        }

        public Criteria andMaTcGreaterThanOrEqualTo(Integer value) {
            addCriterion("ma_tc >=", value, "maTc");
            return (Criteria) this;
        }

        public Criteria andMaTcLessThan(Integer value) {
            addCriterion("ma_tc <", value, "maTc");
            return (Criteria) this;
        }

        public Criteria andMaTcLessThanOrEqualTo(Integer value) {
            addCriterion("ma_tc <=", value, "maTc");
            return (Criteria) this;
        }

        public Criteria andMaTcIn(List<Integer> values) {
            addCriterion("ma_tc in", values, "maTc");
            return (Criteria) this;
        }

        public Criteria andMaTcNotIn(List<Integer> values) {
            addCriterion("ma_tc not in", values, "maTc");
            return (Criteria) this;
        }

        public Criteria andMaTcBetween(Integer value1, Integer value2) {
            addCriterion("ma_tc between", value1, value2, "maTc");
            return (Criteria) this;
        }

        public Criteria andMaTcNotBetween(Integer value1, Integer value2) {
            addCriterion("ma_tc not between", value1, value2, "maTc");
            return (Criteria) this;
        }

        public Criteria andCccdIsNull() {
            addCriterion("CCCD is null");
            return (Criteria) this;
        }

        public Criteria andCccdIsNotNull() {
            addCriterion("CCCD is not null");
            return (Criteria) this;
        }

        public Criteria andCccdEqualTo(String value) {
            addCriterion("CCCD =", value, "cccd");
            return (Criteria) this;
        }

        public Criteria andCccdNotEqualTo(String value) {
            addCriterion("CCCD <>", value, "cccd");
            return (Criteria) this;
        }

        public Criteria andCccdGreaterThan(String value) {
            addCriterion("CCCD >", value, "cccd");
            return (Criteria) this;
        }

        public Criteria andCccdGreaterThanOrEqualTo(String value) {
            addCriterion("CCCD >=", value, "cccd");
            return (Criteria) this;
        }

        public Criteria andCccdLessThan(String value) {
            addCriterion("CCCD <", value, "cccd");
            return (Criteria) this;
        }

        public Criteria andCccdLessThanOrEqualTo(String value) {
            addCriterion("CCCD <=", value, "cccd");
            return (Criteria) this;
        }

        public Criteria andCccdLike(String value) {
            addCriterion("CCCD like", value, "cccd");
            return (Criteria) this;
        }

        public Criteria andCccdNotLike(String value) {
            addCriterion("CCCD not like", value, "cccd");
            return (Criteria) this;
        }

        public Criteria andCccdIn(List<String> values) {
            addCriterion("CCCD in", values, "cccd");
            return (Criteria) this;
        }

        public Criteria andCccdNotIn(List<String> values) {
            addCriterion("CCCD not in", values, "cccd");
            return (Criteria) this;
        }

        public Criteria andCccdBetween(String value1, String value2) {
            addCriterion("CCCD between", value1, value2, "cccd");
            return (Criteria) this;
        }

        public Criteria andCccdNotBetween(String value1, String value2) {
            addCriterion("CCCD not between", value1, value2, "cccd");
            return (Criteria) this;
        }

        public Criteria andNgayTiemIsNull() {
            addCriterion("ngay_tiem is null");
            return (Criteria) this;
        }

        public Criteria andNgayTiemIsNotNull() {
            addCriterion("ngay_tiem is not null");
            return (Criteria) this;
        }

        public Criteria andNgayTiemEqualTo(String value) {
            addCriterion("ngay_tiem =", value, "ngayTiem");
            return (Criteria) this;
        }

        public Criteria andNgayTiemNotEqualTo(String value) {
            addCriterion("ngay_tiem <>", value, "ngayTiem");
            return (Criteria) this;
        }

        public Criteria andNgayTiemGreaterThan(String value) {
            addCriterion("ngay_tiem >", value, "ngayTiem");
            return (Criteria) this;
        }

        public Criteria andNgayTiemGreaterThanOrEqualTo(String value) {
            addCriterion("ngay_tiem >=", value, "ngayTiem");
            return (Criteria) this;
        }

        public Criteria andNgayTiemLessThan(String value) {
            addCriterion("ngay_tiem <", value, "ngayTiem");
            return (Criteria) this;
        }

        public Criteria andNgayTiemLessThanOrEqualTo(String value) {
            addCriterion("ngay_tiem <=", value, "ngayTiem");
            return (Criteria) this;
        }

        public Criteria andNgayTiemLike(String value) {
            addCriterion("ngay_tiem like", value, "ngayTiem");
            return (Criteria) this;
        }

        public Criteria andNgayTiemNotLike(String value) {
            addCriterion("ngay_tiem not like", value, "ngayTiem");
            return (Criteria) this;
        }

        public Criteria andNgayTiemIn(List<String> values) {
            addCriterion("ngay_tiem in", values, "ngayTiem");
            return (Criteria) this;
        }

        public Criteria andNgayTiemNotIn(List<String> values) {
            addCriterion("ngay_tiem not in", values, "ngayTiem");
            return (Criteria) this;
        }

        public Criteria andNgayTiemBetween(String value1, String value2) {
            addCriterion("ngay_tiem between", value1, value2, "ngayTiem");
            return (Criteria) this;
        }

        public Criteria andNgayTiemNotBetween(String value1, String value2) {
            addCriterion("ngay_tiem not between", value1, value2, "ngayTiem");
            return (Criteria) this;
        }

        public Criteria andLanTiemIsNull() {
            addCriterion("lan_tiem is null");
            return (Criteria) this;
        }

        public Criteria andLanTiemIsNotNull() {
            addCriterion("lan_tiem is not null");
            return (Criteria) this;
        }

        public Criteria andLanTiemEqualTo(Integer value) {
            addCriterion("lan_tiem =", value, "lanTiem");
            return (Criteria) this;
        }

        public Criteria andLanTiemNotEqualTo(Integer value) {
            addCriterion("lan_tiem <>", value, "lanTiem");
            return (Criteria) this;
        }

        public Criteria andLanTiemGreaterThan(Integer value) {
            addCriterion("lan_tiem >", value, "lanTiem");
            return (Criteria) this;
        }

        public Criteria andLanTiemGreaterThanOrEqualTo(Integer value) {
            addCriterion("lan_tiem >=", value, "lanTiem");
            return (Criteria) this;
        }

        public Criteria andLanTiemLessThan(Integer value) {
            addCriterion("lan_tiem <", value, "lanTiem");
            return (Criteria) this;
        }

        public Criteria andLanTiemLessThanOrEqualTo(Integer value) {
            addCriterion("lan_tiem <=", value, "lanTiem");
            return (Criteria) this;
        }

        public Criteria andLanTiemIn(List<Integer> values) {
            addCriterion("lan_tiem in", values, "lanTiem");
            return (Criteria) this;
        }

        public Criteria andLanTiemNotIn(List<Integer> values) {
            addCriterion("lan_tiem not in", values, "lanTiem");
            return (Criteria) this;
        }

        public Criteria andLanTiemBetween(Integer value1, Integer value2) {
            addCriterion("lan_tiem between", value1, value2, "lanTiem");
            return (Criteria) this;
        }

        public Criteria andLanTiemNotBetween(Integer value1, Integer value2) {
            addCriterion("lan_tiem not between", value1, value2, "lanTiem");
            return (Criteria) this;
        }

        public Criteria andTenVacXinIsNull() {
            addCriterion("ten_vac_xin is null");
            return (Criteria) this;
        }

        public Criteria andTenVacXinIsNotNull() {
            addCriterion("ten_vac_xin is not null");
            return (Criteria) this;
        }

        public Criteria andTenVacXinEqualTo(String value) {
            addCriterion("ten_vac_xin =", value, "tenVacXin");
            return (Criteria) this;
        }

        public Criteria andTenVacXinNotEqualTo(String value) {
            addCriterion("ten_vac_xin <>", value, "tenVacXin");
            return (Criteria) this;
        }

        public Criteria andTenVacXinGreaterThan(String value) {
            addCriterion("ten_vac_xin >", value, "tenVacXin");
            return (Criteria) this;
        }

        public Criteria andTenVacXinGreaterThanOrEqualTo(String value) {
            addCriterion("ten_vac_xin >=", value, "tenVacXin");
            return (Criteria) this;
        }

        public Criteria andTenVacXinLessThan(String value) {
            addCriterion("ten_vac_xin <", value, "tenVacXin");
            return (Criteria) this;
        }

        public Criteria andTenVacXinLessThanOrEqualTo(String value) {
            addCriterion("ten_vac_xin <=", value, "tenVacXin");
            return (Criteria) this;
        }

        public Criteria andTenVacXinLike(String value) {
            addCriterion("ten_vac_xin like", value, "tenVacXin");
            return (Criteria) this;
        }

        public Criteria andTenVacXinNotLike(String value) {
            addCriterion("ten_vac_xin not like", value, "tenVacXin");
            return (Criteria) this;
        }

        public Criteria andTenVacXinIn(List<String> values) {
            addCriterion("ten_vac_xin in", values, "tenVacXin");
            return (Criteria) this;
        }

        public Criteria andTenVacXinNotIn(List<String> values) {
            addCriterion("ten_vac_xin not in", values, "tenVacXin");
            return (Criteria) this;
        }

        public Criteria andTenVacXinBetween(String value1, String value2) {
            addCriterion("ten_vac_xin between", value1, value2, "tenVacXin");
            return (Criteria) this;
        }

        public Criteria andTenVacXinNotBetween(String value1, String value2) {
            addCriterion("ten_vac_xin not between", value1, value2, "tenVacXin");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TiemChung
     *
     * @mbg.generated do_not_delete_during_merge Tue Mar 12 13:50:13 ICT 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TiemChung
     *
     * @mbg.generated Tue Mar 12 13:50:13 ICT 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}